[APP_INFO]
app_name="APP后台管理程序"
app_version=0.0.0.1

[DEVICE_INFO]
device_name=test_test_test_test_20260316_0001
device_uid=aa0102026031615560001

[APP_CONFIG]
###		00-调试信息（默认）
##		01=Log_Info,    // 普通信息
##		02=Log_Warning, // 警告
##		03=Log_Error,   // 错误
##		04=Log_Fatal    // 致命错误（输出后终止程序）
log_level=00

#		01-控制台
#		02-文本文件
#		03-控制台+文本文件
log_out_mode=01

#		默认控制模式	01-app控制模式		02-手柄控制模式		03-导航控制模式
default_mode=01
tcp_server_port=8080
robot_control_exe="/home/jeffy/Phybot/Phybot-C2/Project/Jeffy/PhybotSoftware_c2/build/main"
robot_control_config="/home/jeffy/Phybot/Phybot-C2/Project/Jeffy/PhybotSoftware_c2/build"

[DEVICE_CONFIG]
#		手柄文件描述符
joystick_file="/dev/input/js0"
audio_mp3_file="/home/amov/project/application_systemd/101"


